apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
